# Generated by Django 5.2.12 on 2026-03-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("status", models.CharField(default="available", max_length=20)),
                (
                    "current_project",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("workload_percent", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TaskBoardProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("priority", models.CharField(default="Medium", max_length=20)),
                ("deadline_days", models.IntegerField(default=14)),
                (
                    "deadline_date",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("status", models.CharField(default="ongoing", max_length=20)),
                ("tasks", models.JSONField(blank=True, default=list)),
                ("team", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
    ]
