# Generated by Django 5.2.12 on 2026-03-14 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0002_activitylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("task_description", models.TextField(blank=True, default="")),
                (
                    "required_skills",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "assigned_to_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "assigned_to_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("sub_task_deadline_days", models.IntegerField(default=1)),
                ("sub_task_deadline_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in-progress", "In Progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("alert_sent", models.BooleanField(default=False)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subtasks",
                        to="agent.employeestatus",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="agent.taskboardproject",
                    ),
                ),
            ],
            options={
                "ordering": ["sub_task_deadline_date", "created_at"],
            },
        ),
    ]
