# Generated by Django 5.2.12 on 2026-03-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0003_subtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeestatus",
            name="source",
            field=models.CharField(default="imported", max_length=20),
        ),
    ]
