# Generated by Django 5.2.12 on 2026-03-15 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0004_employeestatus_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeestatus",
            name="is_outreach",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeestatus",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeestatus",
            name="outreach_project",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="outreach_members", to="agent.taskboardproject"),
        ),
        migrations.AddField(
            model_name="employeestatus",
            name="rate_per_day",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
