# Generated by Django 5.2.12 on 2026-03-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0006_employeeaccount_dailylog_chatmessage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("password_hash", models.CharField(max_length=255)),
                ("registration_locked", models.BooleanField(default=True)),
                ("reset_otp", models.CharField(blank=True, default="", max_length=8)),
                ("reset_otp_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
