from django.urls import path

from .views import (
    ActivitiesView,
    AgentReplanView,
    AgentRunView,
    AnalyticsView,
    EmployeeDetailView,
    EmployeesAddView,
    EmployeesView,
    EmployeeStatusView,
    HistoryView,
    ProjectsView,
    SendAssignmentsView,
    TaskBoardAddMemberView,
    TaskBoardCompleteView,
    TaskBoardCreateView,
    TaskBoardListView,
    TaskBoardRemoveMemberView,
    ToolsView,
)

urlpatterns = [
    path("agent/run/", AgentRunView.as_view(), name="agent-run"),
    path("agent/replan/", AgentReplanView.as_view(), name="agent-replan"),
    path("agent/send-assignments/", SendAssignmentsView.as_view(), name="agent-send-assignments"),
    path("employees/", EmployeesView.as_view(), name="employees"),
    path("employees/add/", EmployeesAddView.as_view(), name="employees-add"),
    path("employees/status/", EmployeeStatusView.as_view(), name="employees-status"),
    path("employees/<str:employee_id>/", EmployeeDetailView.as_view(), name="employee-detail"),
    path("taskboard/", TaskBoardListView.as_view(), name="taskboard-list"),
    path("taskboard/create/", TaskBoardCreateView.as_view(), name="taskboard-create"),
    path("taskboard/<int:project_id>/add-member/", TaskBoardAddMemberView.as_view(), name="taskboard-add-member"),
    path("taskboard/<int:project_id>/remove-member/", TaskBoardRemoveMemberView.as_view(), name="taskboard-remove-member"),
    path("taskboard/<int:project_id>/complete/", TaskBoardCompleteView.as_view(), name="taskboard-complete"),
    path("analytics/", AnalyticsView.as_view(), name="analytics"),
    path("activities/", ActivitiesView.as_view(), name="activities"),
    path("projects/", ProjectsView.as_view(), name="projects"),
    path("tools/", ToolsView.as_view(), name="tools"),
    path("history/", HistoryView.as_view(), name="history"),
]
