from django.urls import path

from .views import (
    ActivitiesView,
    AgentReplanView,
    AgentRunView,
    AnalyticsView,
    CustomMissionView,
    DatasetConfirmView,
    DatasetReloadView,
    DatasetStatusView,
    ProjectBriefPdfConfirmView,
    ProjectBriefPdfUploadView,
    EmployeeDetailView,
    EmployeesDatasetUploadView,
    EmployeesAddOutreachView,
    EmployeesAddView,
    EmployeesView,
    EmployeeStatusView,
    HistoryDatasetUploadView,
    HistoryView,
    ProjectsDatasetUploadView,
    ProjectsView,
    SendAssignmentsView,
    TaskBoardAddMemberView,
    TaskBoardCompleteView,
    TaskBoardCreateView,
    TaskBoardListView,
    TaskBoardRemoveMemberView,
    ToolsDatasetUploadView,
    ToolsView,
)

urlpatterns = [
    path("agent/run/", AgentRunView.as_view(), name="agent-run"),
    path("agent/replan/", AgentReplanView.as_view(), name="agent-replan"),
    path("agent/send-assignments/", SendAssignmentsView.as_view(), name="agent-send-assignments"),
    path("agent/custom-mission/", CustomMissionView.as_view(), name="agent-custom-mission"),
    path("employees/", EmployeesView.as_view(), name="employees"),
    path("employees/add/", EmployeesAddView.as_view(), name="employees-add"),
    path("employees/add-outreach/", EmployeesAddOutreachView.as_view(), name="employees-add-outreach"),
    path("employees/status/", EmployeeStatusView.as_view(), name="employees-status"),
    path("employees/<str:employee_id>/", EmployeeDetailView.as_view(), name="employee-detail"),
    path("taskboard/", TaskBoardListView.as_view(), name="taskboard-list"),
    path("taskboard/create/", TaskBoardCreateView.as_view(), name="taskboard-create"),
    path("taskboard/<int:project_id>/add-member/", TaskBoardAddMemberView.as_view(), name="taskboard-add-member"),
    path("taskboard/<int:project_id>/remove-member/", TaskBoardRemoveMemberView.as_view(), name="taskboard-remove-member"),
    path("taskboard/<int:project_id>/complete/", TaskBoardCompleteView.as_view(), name="taskboard-complete"),
    path("analytics/", AnalyticsView.as_view(), name="analytics"),
    path("analytics/summary/", AnalyticsView.as_view(), name="analytics-summary"),
    path("activities/", ActivitiesView.as_view(), name="activities"),
    path("projects/", ProjectsView.as_view(), name="projects"),
    path("tools/", ToolsView.as_view(), name="tools"),
    path("history/", HistoryView.as_view(), name="history"),
    path("datasets/upload/employees/", EmployeesDatasetUploadView.as_view(), name="datasets-upload-employees"),
    path("datasets/upload/projects/", ProjectsDatasetUploadView.as_view(), name="datasets-upload-projects"),
    path("datasets/upload/tools/", ToolsDatasetUploadView.as_view(), name="datasets-upload-tools"),
    path("datasets/upload/history/", HistoryDatasetUploadView.as_view(), name="datasets-upload-history"),
    path("datasets/upload/projects-brief-pdf/", ProjectBriefPdfUploadView.as_view(), name="datasets-upload-projects-brief-pdf"),
    path("datasets/confirm/", DatasetConfirmView.as_view(), name="datasets-confirm"),
    path("datasets/confirm/projects-brief-pdf/", ProjectBriefPdfConfirmView.as_view(), name="datasets-confirm-projects-brief-pdf"),
    path("datasets/status/", DatasetStatusView.as_view(), name="datasets-status"),
    path("datasets/reload/", DatasetReloadView.as_view(), name="datasets-reload"),
]
